version: "3.8"

services:

  parrot-app-tests:
    image: umahighload/parrot-app:latest
    volumes:
      - ".:/app/src"
    command: bash /app/start-autotests.sh
    depends_on:
      - "parrot-database"
