version: "3.8"

services:

  kesha-tests:
    image: nextuptechnologies/kesha:latest
    volumes:
      - ".:/app/src"
    command: bash /app/start-autotests.sh
    depends_on:
      - "kesha-database"
