# Generated by Django 3.0.6 on 2020-06-25 22:53

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.operations
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.HStoreExtension(
        ),
        migrations.CreateModel(
            name='HTTPStub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=2000, verbose_name='Путь запроса')),
                ('regex_path', models.BooleanField(default=False, help_text='Путь представлен регулярным выражением', verbose_name='REGEX путь')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete'), ('head', 'head'), ('options', 'options'), ('trace', 'trace')], max_length=10, verbose_name='Метод запроса')),
                ('resp_body', models.TextField(blank=True, default='{}', verbose_name='Тело ответа')),
                ('resp_status', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='Статус ответа')),
                ('resp_content_type', models.CharField(default='application/json', max_length=255, verbose_name='Content-type ответа')),
                ('resp_headers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, help_text='Заполняется в формате json', verbose_name='Заголовки ответа')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('body', models.TextField(verbose_name='Тело запроса')),
                ('headers', django.contrib.postgres.fields.hstore.HStoreField(verbose_name='Заголовки запроса')),
                ('source_ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP источника запроса')),
                ('http_stub', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='http_stubs.HTTPStub', verbose_name='Связанная заглушка')),
            ],
        ),
        migrations.AddConstraint(
            model_name='httpstub',
            constraint=models.UniqueConstraint(fields=('path', 'method'), name='uniq-path-method'),
        ),
        migrations.AddField(
            model_name='httpstub',
            name='resp_delay',
            field=models.IntegerField(default=0, help_text='Задаётся в секундах', verbose_name='Задеожка перед ответом'),
        ),
        migrations.AlterModelOptions(
            name='httpstub',
            options={'verbose_name': 'http stub', 'verbose_name_plural': 'stubs'},
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'log', 'verbose_name_plural': 'logs'},
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_body',
            field=models.TextField(blank=True, default='[]', verbose_name='Тело ответа'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_delay',
            field=models.PositiveIntegerField(default=0, help_text='Задаётся в секундах', verbose_name='Задеожка перед ответом'),
        ),
        migrations.AddField(
            model_name='httpstub',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='method',
            field=models.CharField(choices=[('TRACE', 'TRACE'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('GET', 'GET')], db_index=True, max_length=10, verbose_name='Метод запроса'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_delay',
            field=models.PositiveIntegerField(default=0, help_text='Задаётся в милисекундах', verbose_name='Задержка перед ответом'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='path',
            field=models.URLField(default='https://127.0.0.1/test/', verbose_name='Полный путь запроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='method',
            field=models.CharField(choices=[('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('POST', 'POST'), ('HEAD', 'HEAD'), ('GET', 'GET'), ('TRACE', 'TRACE'), ('OPTIONS', 'OPTIONS'), ('PUT', 'PUT')], db_index=True, max_length=10, verbose_name='Метод запроса'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], db_index=True, max_length=10, verbose_name='Метод запроса'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], max_length=10, verbose_name='Метод запроса'),
        ),
    ]
