# Generated by Django 3.0.6 on 2020-06-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('http_stubs', '0001_squashed_0010_auto_20200626_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='http_stub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='http_stubs.HTTPStub', verbose_name='Связанная заглушка'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source_ip',
            field=models.GenericIPAddressField(verbose_name='IP источника запроса'),
        ),
    ]
