# Generated by Django 3.0.6 on 2020-11-18 10:11

import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('http_stubs', '0002_auto_20200626_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpstub',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], db_index=True, max_length=10, verbose_name='Request method'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='path',
            field=models.CharField(db_index=True, max_length=2000, verbose_name='Request path'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='regex_path',
            field=models.BooleanField(default=False, help_text='Path is a regular expression', verbose_name='REGEX path'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_body',
            field=models.TextField(blank=True, default='[]', verbose_name='Response body'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_content_type',
            field=models.CharField(default='application/json', max_length=255, verbose_name='Response Content-Type'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_delay',
            field=models.PositiveIntegerField(default=0, help_text='In milliseconds', verbose_name='Response delay'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_headers',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, help_text='In JSON format', verbose_name='Response headers'),
        ),
        migrations.AlterField(
            model_name='httpstub',
            name='resp_status',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='Response status'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='body',
            field=models.TextField(verbose_name='Request body'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request timestamp'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='headers',
            field=django.contrib.postgres.fields.hstore.HStoreField(verbose_name='Request headers'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='http_stub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='http_stubs.HTTPStub', verbose_name='Related stub'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], max_length=10, verbose_name='Request method'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='path',
            field=models.URLField(verbose_name='Full request path'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='source_ip',
            field=models.GenericIPAddressField(verbose_name='Source IP'),
        ),
    ]
