# Generated by Django 3.1.4 on 2021-03-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_stubs', '0005_httpstub_request_script_logentry_result_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpstub',
            name='enable_logging',
            field=models.BooleanField(default=False, help_text='Enables logging of requests', verbose_name='Logging'),
        ),
    ]
