# Generated by Django 3.1.13 on 2021-10-21 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http_stubs', '0007_add_proxy_stubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='resp_status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='Response status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxylogentity',
            name='resp_status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='Response status'),
            preserve_default=False,
        ),
    ]
